### ISSUE TITLE
Review using Apache Zookeeper instead of Redis

### ISSUE THREAD

**Issue by itayw** [joola/joola#640]
We currently use Redis coupled with server logic to manage both presence and configuration state sharing between nodes.

Zookeeper is designed for this purpose and may be a good replacement for the current way of doing things which is lacking support for real "real-world" big-data scenarios.

**Comment by thedrow** [comment]
Why zookeeper instead of the newer service discovery services such as etcd or consul?
See http://www.consul.io/intro/vs/zookeeper.html and http://devo.ps/blog/zookeeper-vs-doozer-vs-etcd/

**Comment by itayw** [comment]
Hi @thedrow, it's great to hear from you again :)

We are reviewing a few alternatives to our current DYI service discovery/configuration. The article you attached summed up things pretty nicely. Our preference for Zookeeper is as follows:
- Mature, well used with proven abilities.
- Very fast K/V with ACL support which we plan on using.
- Nice fit with existing moving parts. It's already implemented, checkout the feature/#640 branch. 
- Support for leaderhip election which we'll need in the future.

As we tried to do before and as we'll try to do with this, we'll try to end of with an agnostic layer to allow the developer to pick and choose which is the perfect match for their scenario. So, if you already have consul working for you, to have Joola plugin to it instead of requiring you to install Zookeeper.

The current DYI is not good enough to support thousands of events per second while keeping a good track for both availability and configuration updates and we need to move away from it sometime soon.

As always, please continue providing your important feedback.
