### ISSUE TITLE
Issue with simple visualization with Docker container

### ISSUE THREAD

**Issue by smusa** [joola/joola#694]
I inserted the data as suggested in the getting started steps. Docker container is running fine and i could verify the version and sdk. However when i try to use visualization with the simple html Chrome is always complaining about the $ within the script as undefined. I can see the joola.js in it's entirety from the docker container. Below is the html file
<!DOCTYPE html>
...
 src="http://192.168.59.103:8080/joola.js?APIToken=apitoken-demo"></script>
.....
div id="example"></div
script
joola.on("ready",function(){
	
	var options={
		caption:'Visits over Time',
		query:{
			timeframe:'last_hour',
			interval:'minute',
			dimensions:['timestamp'],
			metrics:['visits'],
			collection:'collection-demo'
		}
	};
	$("#example").Timeline(options);
	});
/script
....

**Comment by itayw** [comment]
Hi @smusa, thanks for reporting this issue. 

The issue you're experiencing is due to an incorrect representation in the docs. It uses jquery while never telling you that you need to include it in the page. I'll fix the documentation page to not use jquery, but plain javascript like this:

```js
var options={
    container: '#example',
    caption:'Visits over Time',
    query:{
        timeframe:'last_hour',
        interval:'minute',
        dimensions:['timestamp'],
        metrics:['visits'],
        collection:'collection-demo'
    }
};
new joola.viz.Timeline(options);
```

Can you please give this a try and let me know if you still experience issues?

**Comment by smusa** [comment]
Thank you. I tried this and now i am getting an error in the joola javascript itself:
the addevent in this section (line #10766) is causing the issue.
// Set up auto resize
		if (optionsChart.reflow !== false) {
			addEvent(chart, 'load', function () {
				chart.initReflow();
			});
		}

**Comment by itayw** [comment]
Hi @smusa, did you manage to resolve the issue? Is this ticket still relevant?

**Comment by smusa** [comment]
My apologies for the late reply but i could not resolve the issue because of time constraint on my part. You may close this and i will try it in a new setup. Thank you.
